### ISSUE TITLE
Cannot start REPL after upgrading to 0.12.1.STABLE001

### ISSUE THREAD

**Issue by laurentpetit** [laurentpetit/ccw#590]
Original [issue 549](https://code.google.com/p/counterclockwise/issues/detail?id=549) created by laurentpetit on 2013-03-18T14:17:13.000Z:

<b>What steps will reproduce the problem?</b>
1. Open a project created with a previous version of CCW
2. Hit ctrl-alt-s (open REPL)

<b>What is the expected output? What do you see instead?</b>
Expected: a REPL opens
Actual: After several seconds, a &quot;Waiting for new REPL process ack timed out&quot; dialogue appears, and the console contains:

Exception in thread &quot;main&quot; java.lang.NoClassDefFoundError: clojure/main
Caused by: java.lang.ClassNotFoundException: clojure.main

<b>What version of the product are you using? On what operating system?</b>
Within &quot;install software&quot; in Eclipse it says 0.12.1.STABLE001 (but the release notes say the latest version is 0.12.0.STABLE001, which is slightly confusing).

<b>Please provide any additional information below.</b>

Updating dependencies by right clicking the project -&gt; Leiningen -&gt; update dependencies, appears to fix the problem.
